# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 10:01
from __future__ import unicode_literals

import cred.fields
import cred.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='Title')),
                ('url', models.URLField(blank=True, db_index=True, null=True, verbose_name='URL')),
                ('username', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=250, null=True, verbose_name='Password')),
                ('descriptionmarkdown', models.BooleanField(default=False, verbose_name='Markdown Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('iconname', models.CharField(default=b'Key.png', max_length=64, verbose_name='Icon')),
                ('ssh_key', cred.fields.SizedFileField(blank=True, null=True, storage=cred.storage.CredAttachmentStorage(), upload_to=b'not required', verbose_name='SSH key')),
                ('attachment', cred.fields.SizedFileField(blank=True, null=True, storage=cred.storage.CredAttachmentStorage(), upload_to=b'not required', verbose_name='Attachment')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('modified', models.DateTimeField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ssh_key_name', models.CharField(blank=True, max_length=64, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=64, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group')),
                ('groups', models.ManyToManyField(blank=True, default=None, null=True, related_name='child_creds', to='auth.Group', verbose_name='Groups')),
                ('latest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cred.Cred')),
            ],
        ),
        migrations.CreateModel(
            name='CredAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audittype', models.CharField(choices=[(b'A', 'Added'), (b'C', 'Changed'), (b'M', 'Only Metadata Changed'), (b'V', 'Only Details Viewed'), (b'X', 'Exported'), (b'D', 'Deleted'), (b'S', 'Scheduled For Change'), (b'P', 'Password Viewed')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cred.Cred')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credlogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-time',),
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='CredChangeQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cred.Cred', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cred',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='child_creds', to='cred.Tag', verbose_name='Tags'),
        ),
    ]
